### ISSUE TITLE
Firefox background is not transparent.

### ISSUE THREAD

**Issue by catx0rr** [MiguelRAvila/SimplerentFox#1]
Here's the issue I have encountered.
```
firefox --version      
Mozilla Firefox 77.0.1
```
![image](https://user-images.githubusercontent.com/42901134/85918081-327cd800-b892-11ea-8f90-32f58c538a4b.png)

Turned off all settings on Firefox home content.

![image](https://user-images.githubusercontent.com/42901134/85918165-d9fa0a80-b892-11ea-9bb1-456704db33ed.png)

Placed all files on *chrome* directory inside the $HOME/.mozilla/firefox/XXXXXX/.default-release/

```
pwd                                
/home/[redacted]/.mozilla/firefox/bovgo6mh.default-release/chrome 

ls 
userChrome.css  userChrome__withoutURLBar.css  userContent.css
```
Followed all instructions on about:config of firefox

**Comment by iAmG-r00t** [comment]
Also mine its not transparent, am I missing something.

**Comment by iAmG-r00t** [comment]
Also how do you make it show the time and greetings with name

**Comment by MiguelRAvila** [comment]
> Also how do you make it show the time and greetings with name

Hi! I use this extension !: https://tabliss.io/

**Comment by MiguelRAvila** [comment]
@catx0rr  In the Firefox version I didn't use the background of Firefox transparent, only the `TabBar` and the `URLBar` because of all of the `New Tabs` configuration people can make, But it's a great idea! I'll work on a version with all the background transparent!

**Comment by iAmG-r00t** [comment]
Like we are not getting transparent background when opening a new tab, that's how it should work right?

**Comment by MiguelRAvila** [comment]
@iAmG-r00t Well, yes Only the bars are transparent, TabBar, URLBar and also the Bookmakrs. I made it this way because all of the configurations you can have in the NewTab, But It'll be a great idea for another version, I'll work on it if you think it's a good idea!

**Comment by catx0rr** [comment]
@MiguelRAvila thanks. I've seen your post on FirefoxCSS on reddit, and I think it is a good idea to try it. I like its simplicity.

Alright then looking forward for your next updates. I'll close the issue and will look into your suggestion. Thanks a lot

**Comment by jruaaa** [comment]
@catx0rr you could probably make a rule in content.css and make it collude with picom or whatever compositor you are using. I don't really remember how to do anything but I'm sure you could figure it out. The page id that you'd need to check for is the extension code if you're using tabliss but there are guides online to do that.
