### ISSUE TITLE
Possible css improvments [FF80] [Linux]

### ISSUE THREAD

**Issue by Urimu** [MiguelRAvila/SimplerentFox#15]
For example `.tabbrowser-tabs` doesn't seem to exist (if it ever existed) in FF80 so it can be probably removed. 

And this:
```
.tabbrowser-tab::before {
    opacity: 0 !important;
    border-left: none !important;
}

.tabbrowser-tab::after {
    opacity: 0 !important;
    border-left: none !important;
}
```
Can be simplified to this:

```
.tabbrowser-tab::before,
.tabbrowser-tab::after {
    display: none !important;
}
```
There are few more potential improvements that I spotted but I don't have time to list them all.

**Comment by MiguelRAvila** [comment]
@Urimu Thank you for pointing this out! I'll make some changes in the code to make it cleaner and also in the readme (It's too long right now!) When I clean the code, I'll tell you.

**Comment by Urimu** [comment]
No problem! I'm not using your theme, I was just looking at how you edited the url-bar, so no need to tell me :)

And one more thing, the "popping up" of the url-bar can be solved  by adding back it's border, the border of `#urlbar-background` specifically, just change it's color to be the same as the background color of url-bar and you should be okay. (You might have to add few rules depending on the state of the url-bar)
