### ISSUE TITLE
add-ons not work properly

### ISSUE THREAD

**Issue by yogeshmishra667** [MiguelRAvila/SimplerentFox#16]
![Screenshot (521)](https://user-images.githubusercontent.com/40533800/93501333-eee6b700-f932-11ea-890a-83f5a04a6c15.png)

**Comment by MiguelRAvila** [comment]
Hey! Can you please explain your issue? So I can help you.

**Comment by yogeshmishra667** [comment]
i'm install your add-on theme [here](https://addons.mozilla.org/en-US/firefox/addon/simplerentfox/) but nothing change in my browser also i'm try to install manually but isn't work please help your theme is incredible i want to use it 

when i'm try to manually paste these file
![Capture](https://user-images.githubusercontent.com/40533800/93507008-b21ebe00-f93a-11ea-952d-f68d5a45be5a.JPG)

**Comment by MiguelRAvila** [comment]
Oh, now I can see the problem. You have to choose one file between the compressed and the uncompressed. And rename it.

```
userChrome_WithURLBar.comp.css -> userChrome.css
userChrome_WithURLBar.css -> userChrome.css
```
There should be just one userChrome.css and one userContent.css

And all the other files just the same. It should work!
