### ISSUE TITLE
Composting in dropdown menu.

### ISSUE THREAD

**Issue by b4skyx** [MiguelRAvila/SimplerentFox#2]
![simplescreenrecorder-2020-06-29_09 33 42 (00:00:49 709) 0001](https://user-images.githubusercontent.com/55960554/85972052-7e439480-b9ec-11ea-8e53-d3f69da76080.png)
The contents of the dropdown menu are somewhat unreadable. 
I have blur windows enabled through picom but it does not seems to take an effect in here.
Is there a way to let your compositor handle the firefox composting? 
If not then is it possible to modify the source to configure opacity and color of the drop down in address bar?

**Comment by MiguelRAvila** [comment]
Hi! Yeah there's a way to manage the opacity by yourself! It's actually the last value: `#urlbar-background { background: rgba(20, 20, 20, 0.6) !important; border: none !important; }`

I've just updated it to be an `rbga` value so you can manipulate it by yourself, hope it works!

**Comment by b4skyx** [comment]
I were able to customize it as per my needs, thanks!
Also, is there

**Comment by MiguelRAvila** [comment]
Yes, in the userContent, the last value, you can just comment or delete that rule and you'll see the scrollbar again

**Comment by b4skyx** [comment]
Thanks for guiding me through!
