### ISSUE TITLE
userContent.css missing in linux folder

### ISSUE THREAD

**Issue by fmilani** [MiguelRAvila/SimplerentFox#21]
The README inside linux folder mentions on step 6:

> 6. Then paste the userChrome.css and the userContent.css files into the folder

But there is no userContent.css inside the folder. Is the file missing or is the README wrong?

**Comment by MiguelRAvila** [comment]
Hey @fmilani You're totally right It's missing the `userContent.css` file. My bad. You can use the Windows one (They're the same in both folders) I'll upload the missing file in a while, thanks!

**Comment by MiguelRAvila** [comment]
Done. Missing file added.
