### ISSUE TITLE
show the scrollbar only in private mode?

### ISSUE THREAD

**Issue by Miyazono1** [MiguelRAvila/SimplerentFox#23]
i noticed the scrollbar is hidden, and normally that's fine, but there are certain times i need the scrollbar when in private mode. is there a way to edit the CSS to hide it in normal browsing, but show it in private mode?

**Comment by MiguelRAvila** [comment]
Hey @Miyazono1 !

Yes, you can by deleting (or commenting) thiis code section in the `userContent.css` file: 

```css
:root{
	scrollbar-width: none !important;
}
```

**Comment by Miyazono1** [comment]
i could have sworn i tried that. guess i didn't lmao. thanks!
