### ISSUE TITLE
Can you share your homepage?

### ISSUE THREAD

**Issue by ZEERDEER** [MiguelRAvila/SimplerentFox#48]
Can you share your homepage? thanks[https://raw.githubusercontent.com/migueravila/SimpleFox/master/assets/urlbar.png](url)

**Comment by alaapjoshi** [comment]
https://github.com/migueravila/Bento. Idk how to configure it for Simplefox but I know bento has it.

**Comment by ZEERDEER** [comment]
> https://github.com/migueravila/Bento. Idk how to configure it for Simplefox but I know bento has it.

thank you
