### ISSUE TITLE
Support for macOS

### ISSUE THREAD

**Issue by KhushrajRathod** [MiguelRAvila/SimplerentFox#5]
Hi, could you create a version for macOS? I've tried using the linux version, but it doesn't look how it should look - There's no transparency
Thanks

**Comment by MiguelRAvila** [comment]
@KhushrajRathod Hey! I'm currently working on versions for Windows and some minor fixes for the currently theme. Since I don't have other OS, It's difficult to work on ports, but I'll keep in mind for next releases!

**Comment by KhushrajRathod** [comment]
> @KhushrajRathod Hey! I'm currently working on versions for Windows and some minor fixes for the currently theme. Since I don't have other OS, It's difficult to work on ports, but I'll keep in mind for next releases!

Hi, thanks for working on this and keep up the great work. I'll try to contribute if I can get some time

**Comment by MiguelRAvila** [comment]
Pull Requests are always welcome!
