### ISSUE TITLE
No Url Bar and With url bar are swicheitched in the readme.

### ISSUE THREAD

**Issue by NicTanghe** [MiguelRAvila/SimplerentFox#6]
No Url Bar and With url bar are swicheitched in the readme.

**Comment by MiguelRAvila** [comment]
@NicTanghe  I don't understand the issue, can you explain it better? Is the code in the folders switched?

**Comment by jruaaa** [comment]
He thinks the pictures and the descriptions at the bottom are switched but I'm pretty sure they're not.

**Comment by MiguelRAvila** [comment]
I see, I'll close the Issue then. If any other question, I'll reopen it
