### ISSUE TITLE
Context Menus and Right Click Menus

### ISSUE THREAD

**Issue by jruaaa** [MiguelRAvila/SimplerentFox#7]
Colors in them are kinda wack, I'm going try to hotfix some of MaterialFox's code in.
![image](https://user-images.githubusercontent.com/32626650/89093969-e54dc380-d373-11ea-82f3-53917f047322.png)

**Comment by MiguelRAvila** [comment]
I see, are they clickable? I mean, can you interact with them and only colors are weird? I had some issues with the Windows WM, and they were not clickable. On the other hand if you get it working well please share the code with me (Or make a PR), I don't have Windows in my main computer, so the fixes can be late for this kind of problems. I'll add it to the next to-do fixing.

**Comment by jruaaa** [comment]
Yes, they're fine and I'll pull it. I'm using @MrOtherGuy or u/It_was_the_other_guy firefox css hacks repo to add the dialog boxes and context menu

**Comment by MiguelRAvila** [comment]
@jruaaa Thanks for it! I'll help in everything I can

**Comment by MiguelRAvila** [comment]
@jruaaa I'm gonna make the respective changes to adapt your code to the No URLBar and WithURLBar for windows, thanks for the work!

**Comment by jruaaa** [comment]
Oh shoot sorry forgot about the others. It's copy and paste. I'll do it myself if you haven't already done it by this comment.

**Comment by jruaaa** [comment]
Oh you did it, but what happened to compress vs noncompressed?

**Comment by MiguelRAvila** [comment]
I've done it, Don't worry! Thanks for all the work I keep your contributions in the top of both codes and also the Mr Other Guy contribution (Talking about compressed files, I'm adding them in some minutes)

**Comment by jruaaa** [comment]
One warning, shell and new program opening links are still messed up but I'm mentioning it here: https://github.com/MrOtherGuy/firefox-csshacks/issues/67

**Comment by MiguelRAvila** [comment]
I see, when I have some time, I'm gonna work on it, I'll keep this Issue as open when we have solved it.

**Comment by jruaaa** [comment]
I fixed it in the pull req btw
